In [94]:
import numpy as np 
from itertools import combinations
from tqdm import tqdm

# Total variation on a graph cellular sheaf

In [95]:
V = 4
edges = [
    (1,2),
    (2,3),
    (2,4),
    (1,3)
]

E = len(edges)
d = 5

In [123]:
# Linear maps generation

F_a2 = np.eye(d)
F_c3 = np.eye(d)
F_d4 = np.eye(d)
F_b1 = np.eye(d)

F_b3 = np.random.randn(d,d)
F_a1 = np.random.randn(d,d)
F_c2 = np.linalg.inv(F_a1) @ np.linalg.inv(F_b3)
F_d2 = np.random.randn(d,d)

In [124]:
# Coboundary map

B1 = np.zeros((E*d, V*d))

B1[0:5, 0:5] = -F_a1
B1[0:5, 5:10] = F_b1
B1[5:10, 0:5] = F_a2
B1[5:10, 10:15] = -F_c2
B1[10:15, 5:10] = -F_b3
B1[10:15, 10:15] = -F_c3
B1[15:20, 15:20] = F_d4

In [133]:
# Sheaf Laplacian

L = B1 @ B1.T

In [126]:
N = 100

x_1 = np.random.randn(d,1)
x_2 = F_a1.T @ x_1
x_3 = np.linalg.inv(F_b3.T) @ x_1
x_4 = F_d2.T @ F_a1.T @ x_1

X = np.vstack([x_1, x_2, x_3, x_4])

In [134]:
np.trace(X.T @ L @ X)

876.6719825105126

In [128]:
F_a2.T @ x_2 - F_a1.T @ x_1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [129]:
F_b1.T @ x_1 - F_b3.T @ x_3

array([[ 2.22044605e-16],
       [-3.33066907e-16],
       [-4.44089210e-16],
       [ 3.33066907e-16],
       [ 0.00000000e+00]])

In [130]:
F_c3.T @ x_3 - F_c2.T @ x_2

array([[ 1.33226763e-15],
       [-4.44089210e-16],
       [-6.66133815e-16],
       [ 0.00000000e+00],
       [-8.88178420e-16]])

In [131]:
F_d4.T @ x_4 - F_d2.T @ x_2

array([[ 8.88178420e-16],
       [-1.33226763e-15],
       [-4.44089210e-16],
       [ 4.44089210e-16],
       [-1.33226763e-15]])